-- Mirror of DDL applied directly to the live project.
-- Stores prompt-insights digests generated by the manual GitHub Action workflow.

CREATE TABLE IF NOT EXISTS healthlog.prompt_insights (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  window_start    timestamptz NOT NULL,
  window_end      timestamptz NOT NULL,
  run_count       int         NOT NULL,
  prompt_versions text[]      NOT NULL,
  aggregate       jsonb       NOT NULL,
  synthesis       text        NOT NULL,
  model           text        NOT NULL,
  triggered_by    text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS prompt_insights_created_idx
  ON healthlog.prompt_insights (created_at DESC);

GRANT SELECT, INSERT ON healthlog.prompt_insights TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA healthlog TO service_role;
